# Generated by Django 5.2.13 on 2026-04-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountM",
            fields=[
                (
                    "accode",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("acname", models.CharField(blank=True, max_length=120, null=True)),
                ("grpcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "opbal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("opbaltype", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "db_table": "accountm",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=120, null=True)),
                ("address1", models.CharField(blank=True, max_length=120, null=True)),
                ("address2", models.CharField(blank=True, max_length=120, null=True)),
                ("city", models.CharField(blank=True, max_length=60, null=True)),
                ("state", models.CharField(blank=True, max_length=30, null=True)),
                ("pincode", models.CharField(blank=True, max_length=20, null=True)),
                ("mobile", models.CharField(blank=True, max_length=30, null=True)),
                ("telephone", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.CharField(blank=True, max_length=120, null=True)),
                ("ctype", models.CharField(blank=True, max_length=10, null=True)),
                ("gstno", models.CharField(blank=True, max_length=40, null=True)),
                ("panno", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "clients",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DayBook",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("docdate", models.DateField(blank=True, null=True)),
                (
                    "accode",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, null=True
                    ),
                ),
                ("naration", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("voutype", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "daybook",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DayBookPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("docno", models.CharField(db_index=True, max_length=20)),
                ("accode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "taxamt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
            options={
                "db_table": "daybookpart",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Delpart",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "delpart",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Generali",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("ivalue", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "generali",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Generals",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("cvalue", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "generals",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Itemadj",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "itemadj",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ItemsStk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10)),
                ("stktype", models.CharField(db_index=True, max_length=10)),
                (
                    "qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "qtyb",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "weightb",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "stonewgt",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "stonewgtb",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "opqty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "opqtyb",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "opweight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "opweightb",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "opstonewgt",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "opstonewgtb",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "opstoneamt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "opstoneamtb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "opdmdwgt",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
            ],
            options={
                "db_table": "itemsstk",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Oitemtranm",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "oitemtranm",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Orderd",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "orderd",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Orderm",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "orderm",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Purchased",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "purchased",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Purchasem",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "purchasem",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Purchaserd",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "purchaserd",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Purchaserm",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "purchaserm",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Refineryd",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "refineryd",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Refinerym",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "refinerym",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Repaird",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "repaird",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Repairm",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "repairm",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Salesd",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "salesd",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Salesm",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "salesm",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Salesrd",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "salesrd",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Salesrm",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "salesrm",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SalesType",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("formno", models.CharField(default="", max_length=10)),
                ("prefix", models.CharField(default="", max_length=10)),
                ("pprefix", models.CharField(default="", max_length=10)),
                ("srprefix", models.CharField(default="", max_length=10)),
                ("prprefix", models.CharField(default="", max_length=10)),
            ],
            options={
                "db_table": "salestype",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Smithd",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "smithd",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Smithm",
            fields=[
                (
                    "docno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "smithm",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10)),
                ("menuitem", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "userd",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserHist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10)),
                ("tdate", models.DateField(blank=True, null=True)),
                ("time1", models.CharField(blank=True, max_length=20, null=True)),
                ("time2", models.CharField(blank=True, max_length=20, null=True)),
                ("ip", models.CharField(blank=True, max_length=45, null=True)),
                ("useragent", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "userhist",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserM",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=120, null=True)),
                ("pcode", models.BinaryField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=120, null=True)),
                ("mobile", models.CharField(blank=True, max_length=30, null=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "userm",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "area",
            },
        ),
        migrations.CreateModel(
            name="ClientsAdvanced",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("pincode", models.CharField(blank=True, max_length=30, null=True)),
                ("fax", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "relationperiod",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("relationway", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "relationwayname",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "relationbases",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "relationbasesname",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "purchasepurpose",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "purchasecategory",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "purchasetype",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("working", models.CharField(blank=True, max_length=30, null=True)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("promptorder", models.CharField(blank=True, max_length=10, null=True)),
                ("dtmarriage", models.DateField(blank=True, null=True)),
                ("dtengagement", models.DateField(blank=True, null=True)),
                ("dtbirthday", models.DateField(blank=True, null=True)),
                ("grateinform", models.CharField(blank=True, max_length=10, null=True)),
                ("staffperf", models.CharField(blank=True, max_length=20, null=True)),
                ("properf", models.CharField(blank=True, max_length=20, null=True)),
                ("respperf", models.CharField(blank=True, max_length=20, null=True)),
                ("speedperf", models.CharField(blank=True, max_length=20, null=True)),
                ("cleanperf", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "facilityperf",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "parkfacilityperf",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("contshop", models.CharField(blank=True, max_length=10, null=True)),
                ("recommend", models.CharField(blank=True, max_length=10, null=True)),
                ("area", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "clients_advanced",
            },
        ),
        migrations.CreateModel(
            name="DenominationMaster",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cvalue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "denom_master",
            },
        ),
        migrations.CreateModel(
            name="GiftTable",
            fields=[
                ("points", models.IntegerField(primary_key=True, serialize=False)),
                ("particulars", models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                "db_table": "gifttable",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "items",
            },
        ),
        migrations.CreateModel(
            name="MCTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10)),
                (
                    "weight1",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "weight2",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("mc", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "mcpergm",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "mcperqty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "vaperc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("iqtype", models.CharField(default="", max_length=10)),
            ],
            options={
                "db_table": "mctable",
            },
        ),
        migrations.CreateModel(
            name="PCard",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "vadisc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "totdisc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "pcard",
            },
        ),
        migrations.CreateModel(
            name="Rotable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10)),
                ("model", models.CharField(blank=True, max_length=20, null=True)),
                ("size", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "weight1",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
                (
                    "weight2",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
                ("minqty", models.IntegerField(default=0)),
                ("maxqty", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "rotable",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                "db_table": "route",
            },
        ),
        migrations.CreateModel(
            name="StockType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "is_default",
                    models.SmallIntegerField(db_column="def", db_index=True, default=0),
                ),
                ("compare", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "stktype",
            },
        ),
        migrations.CreateModel(
            name="PartyMCTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pcode", models.CharField(db_index=True, max_length=10)),
                ("icode", models.CharField(db_index=True, max_length=10)),
                ("model", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "wastage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("mc", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "mcperc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "mcperqty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "touch",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("formula", models.CharField(blank=True, max_length=15, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "pmctable",
                "indexes": [
                    models.Index(
                        fields=["pcode", "icode", "model"],
                        name="pmctable_pcode_48d826_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PointCardTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pcard", models.CharField(db_index=True, max_length=10)),
                ("isubgrp", models.CharField(db_index=True, max_length=10)),
                ("pointbasedon", models.CharField(default="Wgt", max_length=10)),
                (
                    "valuefor1point",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valueperpoint",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "minsalesamt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rounddown",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
            ],
            options={
                "db_table": "pcardtable",
                "unique_together": {("pcard", "isubgrp")},
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mtype", models.CharField(max_length=1)),
                ("name", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "models",
                "unique_together": {("mtype", "name")},
            },
        ),
        migrations.CreateModel(
            name="SalesBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_no", models.CharField(max_length=40, unique=True)),
                ("bill_date", models.DateField(blank=True, null=True)),
                ("bill_time", models.CharField(blank=True, max_length=20, null=True)),
                ("bill_type", models.CharField(default="Gold", max_length=30)),
                (
                    "customer_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("mobile", models.CharField(blank=True, max_length=30, null=True)),
                ("gst_no", models.CharField(blank=True, max_length=40, null=True)),
                ("pan_no", models.CharField(blank=True, max_length=30, null=True)),
                ("state_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "rate_per_gm",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "counter_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "counter_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "salesman_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "salesman_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("agent_code", models.CharField(blank=True, max_length=20, null=True)),
                ("approved_by", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cashbank_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "bill_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "exchange_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "return_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "net_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("status", models.CharField(default="saved", max_length=20)),
                ("items_json", models.TextField(blank=True, null=True)),
                ("exchange_json", models.TextField(blank=True, null=True)),
                ("return_json", models.TextField(blank=True, null=True)),
                ("extra_json", models.TextField(blank=True, null=True)),
                (
                    "cancel_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "sales_bills",
                "indexes": [
                    models.Index(
                        fields=["bill_date", "status"],
                        name="sales_bills_bill_da_676f5c_idx",
                    )
                ],
            },
        ),
    ]
